webserver:
  replicas: 12

  image1:
    repository: us-central1-docker.pkg.dev/proven-dryad-417822/hello-app/hello-app
    tag: "v2"

  image2:
    repository: afakharany/watcher
    tag: "latest"

  serviceAccount:
    create: true
    name: "webserver-sa"

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false

  resources:
    requests:
      cpu: 100m
      memory: 64Mi

  autoscaling:
  enabled: false