apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  labels:
{{- include "commonLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
{{- include "commonLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "commonLabels" . | nindent 8 }}
    spec:
      containers:
      - name: webserver
        image: {{ .Values.webserver.image1.repository }}:{{ .Values.webserver.image1.tag }}
        ports:
        - containerPort: 80
      - name: webwatcher
        image: {{ .Values.webserver.image2.repository }}:{{ .Values.webserver.image2.tag }}