apiVersion: v1
kind: Service
metadata:
  labels:
    application: webserver
  name: webserver-deployment
spec:
  type: ClusterIP
  selector:
    application: webserver
  ports:
  - name: http
    port: 80
    targetPort: 80